--1. Tạo csdl bằng lệnh T-sql
--syntax: create database
--tạo csdl đơn giản
use master
go
create database DEV2311LM_SQL24_03
go
--Xoá
DROP DATABASE DEV2311LM_SQL24_03
-- TẠO CSDL VỚI CÁC THUỘC TÍNH CƠ BẢN 
create database DEV2311LM_SQL24_03
ON
( NAME = DEV2311LM_SQL24_03_DATA,
    FILENAME = 'C:\Devmaster.edu.vn\DEV2311LM-SQL24\DATA\DEV2311LM_SQL24_03.mdf',
    SIZE = 10,
    MAXSIZE = 50,
    FILEGROWTH = 5 
)
LOG ON
( NAME = DEV2311LM_SQL24_03_log,
    FILENAME = 'C:\Devmaster.edu.vn\DEV2311LM-SQL24\DATA\DEV2311LM_SQL24_03_log.ldf',
    SIZE = 5MB,
    MAXSIZE = unlimited,
    FILEGROWTH = 5MB 
	);
GO
--2. tạo bảng và các ràng buộc dữ liệu trên bảng
--các kiểu dữ liệu thường dùng
/*
 -- Kiểu số (số nguyên/ số thực): 
 ++ Số nguyên: tinyint/ smallint/ int/ bigint
 ++ Số thực: float/double/ decimal/ numeric
 -- Kiểu chuỗi kí tự (non unicode / unicode)
 ++ non unicode: char/ varchar/ text
 ++ unicode: nchar/ nvarchar/ ntext
 ++  fixed length: char/ nchar
 ++ dynamic length: varchar/nvarchar
 -- Kiểu ngày giờ: smalldatetime/ datetime/ date/ time ,...
 -- Kiểu logic: bit
 -- Kiểu nhị phân: binary
 -- tham khảo thêm: keyword (datatype in sql server https://learn.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql?view=sql-server-ver16)
*/
/* Các ràng buộc dữ liệu trên đối tượng table (Column)
-- null/ not null
-- ràng buộc duy nhất: primary key( k nhận giá trị null) / unique (duy nhất, có nhận giá trị null)/ thuộc tính identity/ kiểu dữ liệu thuộc tính uniqueidentifier
-- ràng buộc tham chiếu (khoá ngoại) foreign key
-- ràng buộc miền giá trị  (domain): datatype (ràng buộc lớn nhất)/ check constraint
-- thuộc tính default: 
* Ràng buộc phức tạp: Sử dụng trigger
*/
--Tạo cấu trúc bảng dữ liệu:
--Syntax: create table
use DEV2311LM_SQL24_03
--2.1. Tạo bảng đơn giản:
Create table TABLE1
(
COL1 INT,
COL2 VARCHAR(100)
)
GO
--2.2. tạo bảng với ràng buộc khoá chính(Primary key)
--VATTU(MAVT, TENVT, DVTINH, PHANTRAM)
CREATE TABLE VATTU
(
MAVTU CHAR(4) PRIMARY KEY,
TENVTU NVARCHAR(200) NOT NULL,
DVT NVARCHAR(20),
PHANTRAM REAL
)
GO
-- XOÁ BẢNG: 
DROP TABLE VATTU
GO
--đẶT TÊN CONSTRAINT
CREATE TABLE VATTU
(
MAVTU CHAR(4) CONSTRAINT PK_VATTU PRIMARY KEY,
TENVTU NVARCHAR(200) NOT NULL,
DVT NVARCHAR(20),
PHANTRAM REAL
)
GO
CREATE TABLE VATTU
(
MAVTU CHAR(4),
TENVTU NVARCHAR(200) NOT NULL,
DVT NVARCHAR(20),
PHANTRAM REAL,
CONSTRAINT PK_VATTU PRIMARY KEY (MAVTU)
)
GO
--NOTE: TẠO BẢNG DỮ LIỆU VỚI KHOÁ CHÍNH TRÊN 2 HAY NHIỀU CỘT
CREATE TABLE TABLE2
(
COL1 INT PRIMARY KEY,
COL2 INT PRIMARY KEY,
COL2 NVARCHAR(100)
)
GO --ERROR
CREATE TABLE TABLE2
(
COL1 INT,
COL2 INT,
COL3 NVARCHAR(100),
CONSTRAINT PK_TABLE1 PRIMARY KEY (COL1, COL2)
)
GO
--2.3. tẠO BẢNG VỚI RÀNG BUỘC KHOÁ CHÍNH VÀ DỮ LIỆU TỰ ĐỘNG TĂNG (IDENTIFY)
-- TABLE3(col1, col2, col3)
CREATE TABLE TABLE3
(
COL1 INT IDENTITY(1,1) CONSTRAINT PK_TABLE3 PRIMARY KEY,
COL2 NVARCHAR(100),
COL3 TINYINT
)
GO
-- 2.4. TẠO BẢNG VỚI RÀNG BUỘC DUY NHẤT (UNIQUE)
-- NHACC(MANCC, TENNCC, DIACHI, DIENTHOAI)
-- PK[MANCC]
--UQ[TENNCC]
CREATE TABLE NHACC
(
MANCC CHAR(3) CONSTRAINT PK_NHACC PRIMARY KEY,
TENNCC NVARCHAR(200) CONSTRAINT UQ_NHACC_TENNCC UNIQUE,
DIACHI NVARCHAR(250),
DIENTHOAI VARCHAR(50) NOT NULL CONSTRAINT UQ_NHACC_DIENTHOAI UNIQUE
)
GO
-- 2.5. TẠO BẢNG VỚI THUỘC TÍNH DEFAULT
-- NHACC(MANCC, TENNCC, DIACHI, DIENTHOAI)
-- PK[MANCC]
--UQ[TENNCC], UQ_DIENTHOAI
--DF[DIACHI] ='25 VŨ NGỌC PHAN'
DROP TABLE NHACC
GO 
CREATE TABLE NHACC
(
MANCC CHAR(3) CONSTRAINT PK_NHACC PRIMARY KEY,
TENNCC NVARCHAR(200) CONSTRAINT UQ_NHACC_TENNCC UNIQUE,
DIACHI NVARCHAR(250) CONSTRAINT DF_NHACC_DIACHI DEFAULT '25 VŨ NGỌC PHAN',
DIENTHOAI VARCHAR(50) NOT NULL CONSTRAINT UQ_NHACC_DIENTHOAI UNIQUE
)
GO
--
DROP TABLE NHACC
GO 
CREATE TABLE NHACC
(
MANCC CHAR(3) CONSTRAINT PK_NHACC PRIMARY KEY,
TENNCC NVARCHAR(200) CONSTRAINT UQ_NHACC_TENNCC UNIQUE,
DIACHI NVARCHAR(250), 
DIENTHOAI VARCHAR(50) NOT NULL CONSTRAINT UQ_NHACC_DIENTHOAI UNIQUE,
CONSTRAINT DF_NHACC_DIACHI DEFAULT '25 VŨ NGỌC PHAN' FOR DIACHI
) -- ERROR
GO
--2.6. rÀNG BUỘC MIỀN GIÁ TRỊ CHECK CONSTRAINT 
-- CTDONDH(SODH, MAVTU, SLDAT)
--PK[SODK, MAVTU]
--CK[SLDAT]>0 -- SLDAT<150
CREATE TABLE CTDONDH
(
SODH CHAR(4),
MAVTU CHAR(4),
SLDAT TINYINT CONSTRAINT CK_CTDONDH_SLDAT CHECK(SLDAT>0 AND SLDAT<150)
CONSTRAINT PK_CTDONDH PRIMARY KEY (SODH, MAVTU)
)
GO
--ĐONH (SODH, NGAYDH, MANHACC)
--PK[SODH]
--DF[NGAYDH] = GETDATE()
PRINT GETDATE()
CREATE TABLE DONDH
(
SODH CHAR(4) CONSTRAINT PK_DONDH PRIMARY KEY,
NGAYDH DATETIME CONSTRAINT DF_DONDH_NGAYDH DEFAULT GETDATE(),
MANHACC CHAR(3)
)
GO
-- 2.7. TẠO BẢNG VỚI RÀNG BUỘC KHOÁ NGOẠI 
-- CTDONDH(SODH, MAVTU, SLDAT)
--PK[SODK, MAVTU]
--CK[SLDAT] SLDAT<100 VÀ SLDAT>0
--FK[SODH]: REFERENCES DONDH
--FK[MAVTU]: REFENCES (THAM CHIẾU) VATTU
DROP TABLE CTDONDH
GO
CREATE TABLE CTDONDH
(
SODH CHAR(4) CONSTRAINT FK_CTDONDH_DONDH_SODH FOREIGN KEY REFERENCES DONDH -- REFERENCES DONDH(SODH)
,MAVTU CHAR(4) --CONSTRAINT FK_CTDONDH_VATTU_SODH FOREIGN KEY REFERENCES VATTU -- REFERENCES VATTU(VATTU)
,SLDAT TINYINT CONSTRAINT CK_CTDONDH_SLDAT CHECK(SLDAT>0 AND SLDAT<150),
CONSTRAINT PK_CTDONDH PRIMARY KEY (SODH, MAVTU),
CONSTRAINT PK_CTDONDH_VATTU_MAVTU FOREIGN KEY (MAVTU)
REFERENCES VATTU --VATTU(MAVTU)
ON UPDATE CASCADE --NO ACTION/ SET NULL/ SET DEFAULT
ON DELETE NO ACTION -- CASCADE / SET NULL / SET DEFAULT
)
GO
--2.8. SỬA ĐỔI BẢNG DONDH
-- BỔ SUNG KHOÁ NGOẠI (MANCC) THAM CHIẾU ĐẾN BẢNG NHACC
--FK[MANHACC] ~ NHACC
--SỬA ĐỔI THÊM RÀNG BUỘC:
ALTER TABLE DONDH
ADD CONSTRAINT FK_DONDH_NHACC  FOREIGN KEY (MANHACC) REFERENCES NHACC(MANCC)
ON UPDATE CASCADE 
ON DELETE NO ACTION
GO 
-- THÊM CỘT 
ALTER TABLE DONDH
ADD TONGTRIGIA NUMERIC(18,2) 
-- XOÁ CỘT
ALTER TABLE ĐONH
DROP COLUMN TONGTRIGIA
GO
-- SỬA TÊN CỘT
EXEC sp_rename 'dbo.DONDH.TONGTRIGIA', 'TONGTRIGIA', 'COLUMN';

--3. làm việc với các câu lệnh dml (select/insert/update/delete)
--3.1. select -> lọc/duyệt/ trích các bản ghi từ nguồn dữ liệu
SELECT*FROM VATTU
GO 
--3.2. INSERT
-- THÊM MỘT HAY NHIỀU BẢN GHI VÀO BẢNG
-- SYNTAX: (ĐƠN GIẢN)
--THÊM MỘT BẢN GHI VÀO BẢNG
INSERT VATTU(MAVTU,TENVTU,DVT,PHANTRAM) -- CÁCH NÀY KHÔNG BẮT BUỘC GIÁ TRỊ PHẢI ĐƯỢC THÊM VÀO CÁC CỘT TƯƠNG ỨNG
VALUES('VT01', N'Tủ lạnh LG204', N'Chiếc', 40)
GO
SELECT * FROM VATTU
INSERT VATTU -- CÁCH NÀY BẮT BUỘC GIÁ TRỊ PHẢI ĐC THÊM VÀO CÁC CỘT TƯƠNG ỨNG, SỐ LƯỢNG PHẢI BẰNG NHAU
VALUES('VT02', N'TỦ LẠNH LG204', N'Chiếc', 40)
GO
INSERT VATTU --Msg 213, Level 16, State 1, Line 233 Column name or number of supplied values does not match table definition.
VALUES('VT02', N'TỦ LẠNH LG204', N'Chiếc')
GO
-- GHI CHÚ: 
--++ CỘT IDENTITY-> MẶC ĐỊNH KHÔNG THỰC HIỆN THÊM GIÁ TRỊ CHO CỘT NÀY
--++ CỘT CÓ GIÁ TRỊ MẶC ĐỊNH HOẶC NULL: CÓ THỂ KHÔNG CẦN THÊM GIÁ TRỊ
--++ MẶC ĐỊNH: KHI THÊM GIÁ TRỊ TRÊN CỘT KHOÁ NGOẠI, THÌ GIÁ TRỊ ĐÓ PHẢI TỒN TẠI TRÊN CỘT THAM CHIẾU TRÊN BẢNG 1 TƯƠNG ỨNG
-- THÊM NHIỀU BẢN GHI CÙNG BẢNG CÙNG LÚC VÀO BẢNG
INSERT VATTU(MAVTU,TENVTU,DVT,PHANTRAM) VALUES
('VT03',N'Tủ lạnh toshiba', N'Chiếc',10),
('VT04',N'Tủ lạnh toshiba', N'Chiếc',15),
('VT05',N'Tủ lạnh toshiba', N'Chiếc',17),
('VT03',N'Tủ lạnh toshiba', N'Chiếc',80)
GO -- ERROR
SELECT*FROM VATTU
INSERT VATTU(MAVTU,TENVTU,DVT,PHANTRAM) VALUES
('VT03',N'Tủ lạnh toshiba', N'Chiếc',10),
('VT04',N'Tủ lạnh toshiba', N'Chiếc',15),
('VT05',N'Tủ lạnh toshiba', N'Chiếc',17),
('VT06',N'Tủ lạnh toshiba', N'Chiếc',80)
GO -- OK
--INSERT SELECT 
INSERT VATTU(MAVTU,TENVTU,DVT,PHANTRAM)
SELECT 'VT09',N'Tủ lạnh toshiba 9', N'Chiếc',10 UNION
SELECT 'VT08',N'Tủ lạnh 
toshiba 8', N'Chiếc',10
------------------------------------------------
--GHI CHÚ: 
/*
- DỮ LIỆU CHUỖI NON UNICODE: ĐẶT TRONG CẶP NHÁY ĐƠN ''
- DỮ LIỆU CHUỖI UNICODE: ĐẶT TRONG CẶP NHÁY ĐƠN N''
- DỮ LIỆU KIỂU NGÀY: (MẶC ĐỊNH)-> ĐẶT TRONG CẶP DẤU NHÁY ĐƠN '', THEO ĐỊNH DẠNG: MM/DD/YYYY HOẶC YYYY/MM/DD
==> SET DATEFORMAT DMY?
*/
--INSERT LÀ CÂU LỆNH THÊM MỘT HOẶC NHIỀU BẢN GHI VÀO BẢNG. ĐÂY LÀ THAO TÁC TRÊN DÒNG TRONG BẢNG. 
--3.3. UPDATE -> SỬA ĐỔI DỮ LIỆU TRÊN CỘT TRONG BẢNG
--XOÁ CŨ, THÊM MỚI: 
-- SYNTAX: 
/* 
UPDATE <TABLE_NAME> [SOURCE]
SET <COLUMN_NAME> = <GIÁ TRỊ> /[<COLUMN_SOURCE>] [,...]
[WHERE <CONDITION>]
*/
-- CẬP NHẬT CỘT PHANTRAM TRONG BẢNG VẬT TƯ, TĂNG LÊN 10:
SELECT*FROM VATTU
--
UPDATE VATTU SET PHANTRAM = PHANTRAM+10
GO
--CẬP NHẬT CỘT PHẦN TRĂM TRONG BẢNG VẬT TƯ, TỈ LỆ PHẦN TRĂM GIẢM ĐI 10 CHO NHỮNG VẬT TƯ CÓ PHẦN TRĂM >=50
UPDATE VATTU SET PHANTRAM = PHANTRAM -10 WHERE PHANTRAM >=50
GO
-- 3.4. XOÁ (DELETE)
--SYNTAX: DELETE [FROM] <TABLE_NAME> [WHERE <CONDITION>]
DELETE VATTU WHERE MAVTU ='VT01'
GO
DELETE VATTU WHERE PHANTRAM<50
GO
SELECT*FROM CTDONDH
-- GHI CHÚ: KHI XOÁ DỮ LIỆU TRÊN BẢNG MÀ CÓ LIÊN KẾT ĐẾN BẢNG BÊN NHIỀU THÌ CHÚ Ý ĐẾN ĐIỀU KIỆN THAM CHIẾU (ON DELETE NO ACTION)
--3.5. XOÁ SẠCH (LÀM SẠCH VÙNG NHỚ)
--SYNTAX: TRUNCATE TABLE <TABLE_NAME>
TRUNCATE TABLE VATTU -- Cannot truncate table 'VATTU' because it is being referenced by a FOREIGN KEY constraint.
GO
TRUNCATE TABLE [DBO].[TABLE3]
GO
NEXT-- CÂU LỆNH SELECT 